language: java

services:
  - rabbitmq

before_install:
    - sudo apt-get install zookeeper
    - sudo apt-get install zookeeper-server
    - sudo service zookeeper-server start

script: ./bin/cucumber
# coveralls
# after_success: mvn clean cobertura:cobertura coveralls:cobertura
